### ISSUE TITLE
Angular example broken in v28

### ISSUE THREAD

**Issue by chefnoname** [ag-grid/examples#18]
When importing docs using the CLI - interface `IOlympicData` isn't imported neither is the 'interfaces' folder imported causing the build to fail
<img width="1728" alt="Screenshot 2022-07-13 at 10 14 09" src="https://user-images.githubusercontent.com/73367271/178697365-ae026e16-914e-4e87-a131-56aaac04fadc.png">

**Comment by StephenCooper** [comment]
Thanks for reporting. Could you help me understand the steps you are taking to get into this situation? Are you copying code from our docs? What do you mean by importing the docs using the CLI?

**Comment by shuheb** [comment]
Fixed on this [commit](https://github.com/ag-grid/examples/commit/4621726622f59ebf84c44fc94e52b3c614776efb)
