### ISSUE TITLE
Angular SSRM import issue

### ISSUE THREAD

**Issue by chefnoname** [ag-grid/examples#20]
If we `t2-import-docs` & select 3 (ssrm example) the files downloaded in the `app.component.ts` are not typescript but HTML

**Comment by shuheb** [comment]
The SSRM documentation pages that the CLI uses to build the examples have now been removed, need to link to another SSRM documentation example.

**Comment by shuheb** [comment]
Fixed on this [commit](https://github.com/ag-grid/examples/commit/4621726622f59ebf84c44fc94e52b3c614776efb)
